# active profiles config
#
# application use two active profiles
#
# one for select repository layer
# ------------------------------------------------
# When using HSQL, use: hsqldb
# When using MySQL, use: mysql
# When using PostgeSQL, use: postgresql
# ------------------------------------------------
#
# one - for select database
# ------------------------------------------------
# When using Spring jpa, use: jpa
# When using Spring JDBC, use: jdbc
# When using Spring Data JPA, use: spring-data-jpa
# ------------------------------------------------

spring:
  profiles:
    active: mysql,spring-data-jpa
  messages:
    basename: messages/messages

# ------------------------------------------------

server:
  port: 8080
#  context-path=/petclinic/


#logging:
#  level:
#    org:
#      springframework=INFO
#logging.level.org.springframework=DEBUG

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# enable the desired authentication type
# by default the authentication is disabled
security:
  ignored: /**
  
basic:
  authentication:
    enabled: false

mybatis:
  mapper-locations: classpath*:org/springframework/samples/petclinic/mapper/*.xml
